create  database  rapido_ ;
use rapido_;

create table  RIDER_
(
RIDER_ID INT PRIMARY KEY ,
RIDER_NAME  VARCHAR (23),
OTP  INT ,
FARE   INT ,
AVALABLE   VARCHAR (34),
JOURNEY   VARCHAR  (32),
TAXI_NO  INT 
);

SELECT * FROM  RIDER_ ; 


CREATE TABLE  CUSTOMER1

(
CUSTOMER_ID  INT PRIMARY KEY ,
CUSTOMER_NAME  VARCHAR (23),
OTP  INT ,
JOURNEY  VARCHAR (23),
foreign key  customer1 (customer_id )  references rider_(rider_id) 
);
SELECT * FROM  CUSTOMER1 ;

SELECT * FROM  RIDER_  INNER JOIN   CUSTOMER1 ON RIDER_.RIDER_ID = CUSTOMER1 . CUSTOMER_ID ;

SELECT* FROM   RIDER_  LEFT JOIN   CUSTOMER1 ON RIDER_.RIDER_ID  = CUSTOMER1 . CUSTOMER_ID  ;

SELECT * FROM  RIDER_  RIGHT JOIN CUSTOMER1  ON RIDER_.RIDER_ID  =  CUSTOMER1 . CUSTOMER_ID ;

SELECT * FROM  RIDER_ CROSS JOIN  CUSTOMER1 ;
